var courses = {
    "courses": [
        {"id":"0","name": "CS 281: Computer Architecture", "level": "Masters", "semester": "Spring","career":"Computer Science","levelVal":"1","semesterVal":"0","careerVal":"0", "credhours":"3","instructor":"Harshada Manu","duration":"1/17/18 - 5/12/18", "rating":2, "totalseats":30, "seatstaken":30,"image": "comparch.jpg","desc":"Includes the organization and architecture of computer systems hardware; instruction set architectures; addressing modes; register transfer notation; processor design and computer arithmetic; memory systems; hardware implementations of virtual memory, and input/output control and devices."},
        {"id":"1","name": "CS 331: Operating Systems","level": "Masters","semester": "Summer", "career":"Computer Science","levelVal":"1","semesterVal":"1","careerVal":"0", "credhours":"3","instructor":"Ya Xiang","duration":"6/1/18 - 8/4/18", "rating":4, "totalseats":30, "seatstaken":23,"image": "os.jpg","desc": "Introduces operating system concepts for single-user systems. Topics include hardware management, file and memory management, system configuration/optimization, and utilities." },
        {"id":"2","name": "CS 191: Discrete Mathematics I", "level": "Masters","semester": "Fall","career":"Computer Science","levelVal":"1","semesterVal":"2","careerVal":"0", "credhours":"3","instructor":"Vimal Deo","duration":"1/17/18 - 5/12/18", "rating":3, "totalseats":30, "seatstaken":23,"image": "discmath.png","desc": "Discrete mathematics forms the mathematical foundation of computer and information science."},
        {"id":"3","name": "CS 590: Cloud Computing", "level": "Doctorate","semester": "Summer","career":"Computer Science","levelVal":"2","semesterVal":"1","careerVal":"0", "credhours":"3","instructor":"Urvi Amar","duration":"8/18/18-12/15/18", "rating":3, "totalseats":30, "seatstaken":14,"image": "cloud.jpg","desc": "The SaaS and PaaS topics covered in the course will familiarize students with the use of vendor-maintained applications and processes available on the Cloud on a metered on-demand basis in multi-tenant environments." },
        {"id":"4","name": "CS 101: Introduction to Python", "level": "Bachelors", "semester": "Fall","career":"Computer Science","levelVal":"0","semesterVal":"2","careerVal":"0", "credhours":"3","instructor":"Vasili Matvey","duration":"8/18/18-12/15/18", "rating":5, "totalseats":30, "seatstaken":29,"image": "python.jpg","desc": "Introduction to the Python programming language for students without prior programming experience. We cover data types, control flow, object-oriented programming, and graphical user interface-driven applications"},

        {"id":"5","name": "ECE 110: Thermodynamics","level": "Bachelors","semester": "Summer", "career":"Electrical Engineering","levelVal":"0","semesterVal":"1","careerVal":"1","credhours":"3","instructor":"Indrajit Kavi","duration":"6/1/18 - 8/4/18", "rating":3, "totalseats":30, "seatstaken":13,"image": "thermo.jpg","desc": "Covers principles of classical thermodynamics. Develops understanding of mass, energy, heat, work, efficiency, ideal and real thermodynamic cycles and processes. " },
        {"id":"6","name": "ECE 317: Digital Signal Processing", "level": "Doctorate","semester":"Spring","career":"Electrical Engineering","levelVal":"2","semesterVal":"0","careerVal":"1","credhours":"3","instructor":"Sarika Isha","duration":"6/1/18 - 8/4/18", "rating":5, "totalseats":30, "seatstaken":25,"image":"dp.jpg","desc": "A thorough understanding of digital signal processing fundamentals and techniques is essential for anyone whose work is concerned with signal processing applications." },
        {"id":"7","name": "ECE 225: Circuit Analysis", "level": "Bachelors","semester": "Summer","career":"Electrical Engineering","levelVal":"0","semesterVal":"1","careerVal":"1","credhours":"3","instructor":"Shura Svyatopolk","duration":"1/17/18 - 5/12/18", "rating":2,"totalseats":30, "seatstaken":26,"image":"circuits.jpg","desc": "Upon successful completion of this course, students should be able to: analyze small RLC circuits by hand. use network techniques, like node analysis and loop analysis, to write equations for large linear circuits."},
        {"id":"8","name": "ECE 266: Logic Design", "level": "Masters","semester": "Fall","career":"Electrical Engineering","levelVal":"1","semesterVal":"2","careerVal":"1","credhours":"3","instructor":"Punita Surinder","duration":"8/18/18-12/15/18", "rating":4, "totalseats":30, "seatstaken":17,"image":"logicgates.png","desc": "This course presents the introductory concepts that are needed in order to design digital systems. Classical methods, including Boolean algebra, combinational and sequential logic design methods."},
        {"id":"9","name": "ECE 341: Probability and Random Processes", "level": "Doctorate","semester": "Fall","career":"Electrical Engineering","levelVal":"2","semesterVal":"2","careerVal":"1","credhours":"3","instructor":"Qiang Guanting","duration":"8/18/18-12/15/18", "rating":5, "totalseats":30, "seatstaken":1,"image": "prob.png","desc": "Topics include: axiomatic probability theory; discrete and continuous random variables; functions of random variables; generating functions and transform methods; inequalities, bounds and large deviation theory, and convergence and limit theorems."},

        {"id":"10","name": "LAW 510: Intro to Copyright Law","level": "Masters", "semester": "Spring","career":"Law","levelVal":"1","semesterVal":"0","careerVal":"2","credhours":"3","instructor":"Kemp Wade","duration":"1/17/18 - 5/12/18", "rating":1, "totalseats":30, "seatstaken":26,"image": "copyright.jpg","desc": "Topics covered include: structure of federal law; basics of legal research; legal citations."},
        {"id":"11","name": "PS 170: American Government", "level": "Bachelors", "semester": "Spring", "career":"Law","levelVal":"0","semesterVal":"0","careerVal":"2","credhours":"3","instructor":"Everett Kurt","duration":"1/17/18 - 5/12/18", "rating":4, "totalseats":30, "seatstaken":24,"image":"govt.jpg","desc": "This course is a study of the origins, development, structure, and functions of American national government. Topics include the constitutional framework; federalism; the three branches of government, including the bureaucracy; civil rights and liberties; political participation and behavior; and policy formation." },
        {"id":"12","name": "PS 225: Democracy:Ancient and Modern", "level": "Bachelors", "semester": "Summer", "career":"Law","levelVal":"0","semesterVal":"1","careerVal":"2","credhours":"3","instructor":"Edwyn Bradford","duration":"1/17/18 - 5/12/18", "rating":3, "totalseats":30, "seatstaken":6,"image":"democracy.jpg","desc": "The course will offer students with a wide range of interests (e.g., politics, public policy, ethics, law, literature, history, the ancient world) a unique opportunity to look at democracy through a fresh lens."},
        {"id":"13","name": "PY 300: Natural Law", "level": "Bachelors", "semester": "Fall", "career":"Law","levelVal":"0","semesterVal":"2","careerVal":"2","credhours":"3","instructor":"Bradley Ross","duration":"8/18/18-12/15/18", "rating":2, "totalseats":30, "seatstaken":20,"image":"natlaw.jpg","desc": "This course traces the origins and consequences of the theory of natural law. Natural law is the idea that there is an objective moral order."},
        {"id":"14","name": "LAW 904: Supreme Court Litigation", "level": "Masters", "semester": "Fall", "career":"Law","levelVal":"1","semesterVal":"2","careerVal":"2","credhours":"3","instructor":"Gina Linsey","duration":"8/18/18-12/15/18", "rating":2, "totalseats":30, "seatstaken":16,"image": "supreme.jpg","desc": "The Supreme Court Litigation Clinic will expose students to the joys and frustrations of litigation before the Supreme Court."}
    ]
}

var levels = ["Bachelors", "Masters","Doctorate"];
var semesters = ["Spring", "Summer","Fall"];
var careers = ["Computer Science", "Electrical Engineering","Law"];